### ISSUE TITLE
Ultrasound conflicting with Video Recording in multiple social media apps

### ISSUE THREAD

**Issue by bhagirathbhard** [aydenp/Ultrasound#1]
Multiple apps like Instagram, WhatsApp, Snapchat allow you to start recording video by holding down the volume down button. 

While having ultrasound, that functionality breaks.

**Comment by aydenp** [comment]
Does it work in the stock camera app?

**Comment by bhagirathbhard** [comment]
Yes

________________________________

**Comment by bhagirathbhard** [comment]
@aydenp It works only in the camera app but if you try it on snapchat,instagram,whatsapp anything else it invokes ultrasound volume control rather than the record functionality.

**Comment by aydenp** [comment]
I'll take a look. Thanks!

**Comment by aydenp** [comment]
Works fine for me here. You most likely have another tweak interfering with the buttons. Try disabling other tweaks in iCleaner.

**Comment by bhagirathbhard** [comment]
Fixed it working by allowing snapchat on unsub and liberty lite.
