### ISSUE TITLE
Constant timeouts

### ISSUE THREAD

**Issue by bobodoll131** [aydenp/Ultrasound#15]
Looks great, and usually works fine on iOS 12.1.2 XS

However, when I press the volume buttons once at a time instead of pressing and holding, the HUD constantly appears and disappears on each press. So if I start at 25%, pressing once'll change the volume to 31%, which the HUD will register. But then it'll automatically time out, appearing again if I press any volume key, ad nauseum. Instead of waiting until no volume changes are registered, then timing out. This doesn't affect functionality, but is extremely annoying. This issue only appeared with the latest update v1.2.13

**Comment by aydenp** [comment]
I'm sorry that you're experiencing this issue, it sounds quite annoying. Could you attach a video or screen recording of it occurring? It would likely provide some helpful hints as to what may be the underlying cause.
