### ISSUE TITLE
SpringBoard's keyboard is stuck portrait on iPad

### ISSUE THREAD

**Issue by jakeajames** [aydenp/Ultrasound#2]
iPad users will have their keyboard stuck in portrait mode in SpringBoard.

To reproduce:
- go to landscape mode
- trigger Ultrasound at least once
- open Spotlight menu

**Comment by Haeckli** [comment]
I can confirm this exact behaviour. iPadAir2, IOS 12.1.1 
Seem to only affect spotlight search; havn't seen the effect in any apps yet...

**Comment by aydenp** [comment]
Likely linked to the window we create and how its meant to stay in portrait, will take a look

**Comment by jakeajames** [comment]
I remember @the-casle had the same issue with Nine, I don't know if he ever fixed it, maybe he could help

**Comment by aydenp** [comment]
Further testing on the latest release version confirms that this was fixed by 6664eb68.
