### ISSUE TITLE
Haptic feedback doesn’t work on iPhone 5S at iOS 12.4

### ISSUE THREAD

**Issue by s0m3sushi** [aydenp/Ultrasound#5]
When reached 100% users won’t be able to get the haptic feedback after enabling it.
Steps to reproduce:
1. Enable haptic feedback
2. Turn the volume up to 100%

**Comment by halkun** [comment]
Seeing the same issue on my iPhone SE with iOS 12.4.
Side note and previously, this issue was observed on iOS 12.1.1 as well.

No feedback comes up when volumes were both at 0% and 100%.

When using Aerify tweak, I do get haptic feedback at 100%. I don't recall it at 0% though.

**Comment by PatrikTheDev** [comment]
I think the reason is that the 5S doesn’t have the Taptic Engine, so it’s incapable of giving haptics.

**Comment by aydenp** [comment]
This is correct. We can't provide Haptic Feedback on the 5s or 6, as the 6s was the first to ship with a Taptic Engine. The current minimum supported device for Haptic Feedback is iPhone 7, as it has a newer and more precise engine supported by newer APIs (leaving out the 6s and SE as well).

**Comment by aydenp** [comment]
I'm going to close this and open #7, which tackles the issue for newer devices specifically.
