### ISSUE TITLE
Enable Haptic Feedback on first-generation Taptic Engine

### ISSUE THREAD

**Issue by aydenp** [aydenp/Ultrasound#7]
iPhone 6s has an inferior Taptic Engine which is not supported by the APIs currently used. Look into enabling this with the use of APIs that do work on the 6s to see if it is capable of supporting the required experience, and if so, switch to that API.

**Comment by PatrikTheDev** [comment]
I think it would be just better to not switch to it and only do it if it’s running on an older iPhone. Also the SE doesn’t have a Taptic Engine.

**Comment by aydenp** [comment]
You're right, grouped it because release date. This issue is then just about iPhone 6s

**Comment by PatrikTheDev** [comment]
The current (iPhone 7<) API is much superior to just playing system sounds (that are the haptics). But sadly that’s the only way on the 6s

**Comment by aydenp** [comment]
Yeah, it's not optimal, but I think slightly inferior Haptic on the 6s is most likely a better experience, especially when our use of Haptic is pretty simple. Just in case though, I mentioned '[seeing] if it is capable of supporting the required' expectations, so if it feels much worse (either on the 6s alone or all devices -- depending on if we switch all of the devices to the inferior API or only use it for the 6s) it can be left out.

**Comment by PatrikTheDev** [comment]
I misunderstood at first, sorry. I thought you wanted to fully transition to the old API for all devices, because that would be a downgrade.
